Changing dependencies requirements to be compliant with EBRAINS ESD
NeuralEnsemble/cobrawap pull request #83
Opened 2024-12-10 09:05 UTC by cosimolupo

In this Pull Request, the requirements of Cobrawap dependencies have been aligned to the latest [EBRAINS Software Distribution (ESD) guidelines](https://gitlab.ebrains.eu/ri/tech-hub/platform/esd/ebrains-spack-builds).

In more detail, referring to the `pyproject.toml` file:
- the "<0.12" requirement on `neo` has been removed, since the presence of `|`'s in config filenames does not seem to be an issue, at variance with initial guess (see also issue #81 for a discussion on the use of `|`'s in filenames);
- the `ruamel.yaml` version requirement has been slightly changed from ">=0.18.3" to "==0.17.32", in order to have an already compiled version also available via [spack](https://packages.spack.io/package.html?name=py-ruamel-yaml);
- the `pulp` dependency has been explicitly added and pinned to "<2.8", so to be compatible with the current constraint "<8.0" for `snakemake` (see also issues #57 and #82).

In addition, `requirements/environment-docs.yaml` file has been updated accordingly.

Finally, there is a potential change to be done also on `scikit-image`, i.e. relax the version requirement from ">=0.20.0" to ">=0.19.0", so to exploit an already built package in the [ESD pipeline](https://gitlab.ebrains.eu/ri/tech-hub/platform/esd/ebrains-spack-builds). Further checks are needed in this regard.

2025-02-26 14:12 UTC, rgutzen requested changes

2025-02-26 14:12 UTC, rgutzen commented on pyproject.toml
> -    "neo >= 0.10.2, < 0.12",
loading a test .nix file with the load_neo function seems to work with and without a '|' in the file name

2025-02-26 14:45 UTC, cosimolupo commented on pyproject.toml
>      "scikit-image >= 0.20.0",
Change "scikit-image" version from 0.20 to 0.19 for a faster build in GitLab EBRAINS ESD.

2025-02-28 21:04 UTC, gulpgiulia commented on pyproject.toml
> +    { name = "Cobrawap authors and contributors" }
let's explore alternatives for creating a common contact point (e.g. info@cobrawap), such that our personal email address should not be explicitly listed, but still are reached through the common point.
E.g. zimbra

2025-03-05 10:52 UTC, cosimolupo commented on pyproject.toml
> +    { name = "Cobrawap authors and contributors" }
Great, thanks! So at this point we can commit this suggestion, right?

2025-03-05 12:10 UTC, mdenker commented on pyproject.toml
> +    { name = "Cobrawap authors and contributors" }
@rgutzen If you approve this solution?

2025-03-05 14:01 UTC, rgutzen approved these changes

2025-03-05 14:09 UTC, merged